version: '3.3'
services:

  frontend:
    image: nooneliveshere/foodgram_frontend:latest
    volumes:
      - ../frontend/:/app/result_build/

  nginx:
    image: nginx:1.19.3
    container_name: nginx-container
    ports:
      - "80:80"

    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_value:/var/html/backend_static/
      - media_value:/var/html/media/
    depends_on:
      - backend

  backend:
    build:
       context: ../backend/
       dockerfile: Dockerfile
    container_name: backend-container
    restart: always

    volumes:
      - static_value:/app/backend_static/
      - media_value:/app/media/
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: postgres:13.0-alpine
    container_name: database-container

    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"

volumes:
  static_value:
  media_value:
  db_data: